### ISSUE TITLE
inconsistency about the project's name

### ISSUE THREAD

**Issue by nbehrnd** [novoid/guess-filename.py#2]
On GitHub, it is `guess-filename.py` in the address and `guessfilename.py` to start the documentation.  On PyPi and the subsequent command on the CLI are `guessfilename` only.

The use of one name in common were preferred. So far, I have not (yet) been successful to identify a reference if renaming the project (and address) into the form without `.py` is possible by some sort of GitHub redirect which would preserve the links between the project on GitHub and the watchers, stargazers, etc.

**Comment by nbehrnd** [comment]
In reply to «How do I rename a repository on GitHub?» on
stackoverflow,[1] user VonC reports since 2013 GitHub automatically
manages the necessary details.  Because the documentation he mentions
still is online[2] -- including a (c) by 2022 -- there shouldn't be an
obstacle to consolidate the name and web address about guessfilename.


[1]
https://stackoverflow.com/questions/5751585/how-do-i-rename-a-repository-on-github
[2]
https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by novoid** [comment]
First: you are absolutely right. **I did not pay attention in creating a consistent naming scheme** which caused this mess you're describing.

I guess my original intention was to "mark" this tool as a Python one by adding ".py" to its repository name. This does not provide any benefit for the CLI execution as a user and therefore I might have omitted the ".py" in the alias I created.

So what about now?

Fixing this mess is not an easy job to do. I refrain from renaming this repository because this would break all existing links which are many. I could maybe find all my own references which are scattered across many blog articles and project READMEs. I can not fix links published in talks and slide-sets. Therefore, I can not rename this repository.

Adding a useless ".py" to the CLI alias would not provide any benefit from my point of view.

Maybe I fix that stupid inconsistency when I follow my "migrate everything from GitHub to a more free alternative" which will break stuff anyway. This is very low priority at the bottom of my list of projects. I won't give it much chances unless Microsoft gets even more evil in future.

Therefore, I can only beg for forgiveness for this mess I've caused.
